CREATE TABLE MONETARYDONATIONS(

ID INT NOT NULL PRIMARY KEY IDENTITY,
DONORNAME VARCHAR(100) NOT NULL,
DATE VARCHAR(100) NOT NULL,
AMOUNT VARCHAR(255) NOT NULL,
CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP

);

CREATE TABLE NEWGOODSDONATIONS(

ID INT NOT NULL PRIMARY KEY IDENTITY,
DESCRIPTION VARCHAR(100) NOT NULL,
CATEGORY VARCHAR(100) NOT NULL,
NUMBEROFITEMS VARCHAR(255) NOT NULL,
DATE VARCHAR(255) NOT NULL,
CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP

);


INSERT INTO MONETARYDONATIONS(DONORNAME, DATE, AMOUNT)
VALUES
('ADAM', '20 JUNE 2022', '20000');

INSERT INTO NEWGOODSDONATIONS(DESCRIPTION, CATEGORY, NUMBEROFITEMS, DATE)
VALUES
('FOOD', 'FOOD', '2 ITEMS', '3 JUNE 2022');